# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/Gui/mockup.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        self.cb_timeUnit = QtWidgets.QComboBox(self.frame_ulOpt)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 530)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(407, 800))
        self.main_widget = QtWidgets.QWidget(MainWindow)
        self.main_widget.setObjectName("main_widget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.main_widget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.frame_welcome = QtWidgets.QFrame(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_welcome.sizePolicy().hasHeightForWidth())
        self.frame_welcome.setSizePolicy(sizePolicy)
        self.frame_welcome.setMinimumSize(QtCore.QSize(385, 75))
        self.frame_welcome.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_welcome.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_welcome.setObjectName("frame_welcome")
        self.btn_signIn = QtWidgets.QPushButton(self.frame_welcome)
        self.btn_signIn.setGeometry(QtCore.QRect(280, 40, 93, 28))
        self.btn_signIn.setObjectName("btn_signIn")
        self.lbl_welcome = QtWidgets.QLabel(self.frame_welcome)
        self.lbl_welcome.setGeometry(QtCore.QRect(48, 10, 329, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_welcome.sizePolicy().hasHeightForWidth())
        self.lbl_welcome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_welcome.setFont(font)
        self.lbl_welcome.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.lbl_welcome.setObjectName("lbl_welcome")
        self.lbl_pic = QtWidgets.QLabel(self.frame_welcome)
        self.lbl_pic.setGeometry(QtCore.QRect(10, 10, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pic.sizePolicy().hasHeightForWidth())
        self.lbl_pic.setSizePolicy(sizePolicy)
        self.lbl_pic.setMinimumSize(QtCore.QSize(32, 32))
        self.lbl_pic.setMaximumSize(QtCore.QSize(32, 32))
        self.lbl_pic.setBaseSize(QtCore.QSize(32, 32))
        self.lbl_pic.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_pic.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_pic.setLineWidth(1)
        self.lbl_pic.setText("")
        self.lbl_pic.setPixmap(QtGui.QPixmap(":/me.jpg"))
        self.lbl_pic.setScaledContents(True)
        self.lbl_pic.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_pic.setObjectName("lbl_pic")
        self.vboxlayout.addWidget(self.frame_welcome)
        self.frame_options = QtWidgets.QTabWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_options.sizePolicy().hasHeightForWidth())
        self.frame_options.setSizePolicy(sizePolicy)
        self.frame_options.setObjectName("frame_options")
        self.frame_info = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_info.sizePolicy().hasHeightForWidth())
        self.frame_info.setSizePolicy(sizePolicy)
        self.frame_info.setObjectName("frame_info")
        self._3 = QtWidgets.QFormLayout(self.frame_info)
        self._3.setObjectName("_3")
        self.lbl_cw = QtWidgets.QLabel(self.frame_info)
        self.lbl_cw.setObjectName("lbl_cw")
        self._3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_cw)
        self.sb_cw = QtWidgets.QSpinBox(self.frame_info)
        self.sb_cw.setSuffix("")
        self.sb_cw.setMinimum(1)
        self.sb_cw.setMaximum(150)
        self.sb_cw.setProperty("value", 35)
        self.sb_cw.setDisplayIntegerBase(10)
        self.sb_cw.setObjectName("sb_cw")
        self._3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sb_cw)
        self.lbl_date = QtWidgets.QLabel(self.frame_info)
        self.lbl_date.setObjectName("lbl_date")
        self._3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_date)
        self.dt_date = QtWidgets.QDateEdit(self.frame_info)
        self.dt_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 4, 26), QtCore.QTime(0, 0, 0)))
        self.dt_date.setMaximumDate(QtCore.QDate(2020, 12, 31))
        self.dt_date.setMinimumDate(QtCore.QDate(2016, 1, 1))
        self.dt_date.setDisplayFormat("dd/MMM/yyyy, dddd")
        self.dt_date.setCalendarPopup(True)
        self.dt_date.setObjectName("dt_date")
        self._3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dt_date)
        self.lbl_topic = QtWidgets.QLabel(self.frame_info)
        self.lbl_topic.setObjectName("lbl_topic")
        self._3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_topic)
        self.cb_topic = QtWidgets.QComboBox(self.frame_info)
        self.cb_topic.setObjectName("cb_topic")
        self.cb_topic.addItem("")
        self.cb_topic.addItem("")
        self._3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_topic)
        self.lbl_description = QtWidgets.QLabel(self.frame_info)
        self.lbl_description.setObjectName("lbl_description")
        self._3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_description)
        self.txt_description = QtWidgets.QPlainTextEdit(self.frame_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_description.sizePolicy().hasHeightForWidth())
        self.txt_description.setSizePolicy(sizePolicy)
        self.txt_description.setMinimumSize(QtCore.QSize(230, 45))
        self.txt_description.setMaximumSize(QtCore.QSize(230, 90))
        self.txt_description.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByMouse | QtCore.Qt.TextEditable | QtCore.Qt.TextEditorInteraction |
            QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse)
        self.txt_description.setPlaceholderText("")
        self.txt_description.setObjectName("txt_description")
        self._3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_description)
        self.frame_options.addTab(self.frame_info, "")
        self.frame_ulOpt = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_ulOpt.sizePolicy().hasHeightForWidth())
        self.frame_ulOpt.setSizePolicy(sizePolicy)
        self.frame_ulOpt.setObjectName("frame_ulOpt")
        self._4 = QtWidgets.QFormLayout(self.frame_ulOpt)
        self._4.setObjectName("_4")
        self.txt_ulInterval = QtWidgets.QLabel(self.frame_ulOpt)
        self.txt_ulInterval.setObjectName("txt_ulInterval")
        self._4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.txt_ulInterval)
        self.sb_time = QtWidgets.QSpinBox(self.frame_ulOpt)
        self.sb_time.setProperty("value", 5)
        self.sb_time.setObjectName("sb_time")
        self._4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sb_time)
        self.cb_timeUnit.setObjectName("cb_timeUnit")
        self.cb_timeUnit.addItem("")
        self.cb_timeUnit.addItem("")
        self._4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_timeUnit)
        self.cb_fileSave = QtWidgets.QCheckBox(self.frame_ulOpt)
        self.cb_fileSave.setObjectName("cb_fileSave")
        self._4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_fileSave)
        self.lbl_fileName = QtWidgets.QLabel(self.frame_ulOpt)
        self.lbl_fileName.setObjectName("lbl_fileName")
        self._4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_fileName)
        self.txt_fileName = QtWidgets.QLineEdit(self.frame_ulOpt)
        self.txt_fileName.setMaxLength(40)
        self.txt_fileName.setClearButtonEnabled(True)
        self.txt_fileName.setObjectName("txt_fileName")
        self._4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_fileName)
        self.frame_options.addTab(self.frame_ulOpt, "")
        self.frame_nbOpt = QtWidgets.QWidget()
        self.frame_nbOpt.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_nbOpt.sizePolicy().hasHeightForWidth())
        self.frame_nbOpt.setSizePolicy(sizePolicy)
        self.frame_nbOpt.setObjectName("frame_nbOpt")
        self._2 = QtWidgets.QFormLayout(self.frame_nbOpt)
        self._2.setObjectName("_2")
        self.frame_browse = QtWidgets.QFrame(self.frame_nbOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_browse.sizePolicy().hasHeightForWidth())
        self.frame_browse.setSizePolicy(sizePolicy)
        self.frame_browse.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_browse.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_browse.setLineWidth(0)
        self.frame_browse.setObjectName("frame_browse")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_browse)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_folderLocation = QtWidgets.QLineEdit(self.frame_browse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_folderLocation.sizePolicy().hasHeightForWidth())
        self.txt_folderLocation.setSizePolicy(sizePolicy)
        self.txt_folderLocation.setObjectName("txt_folderLocation")
        self.horizontalLayout.addWidget(self.txt_folderLocation)
        self.btn_browse = QtWidgets.QPushButton(self.frame_browse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_browse.sizePolicy().hasHeightForWidth())
        self.btn_browse.setSizePolicy(sizePolicy)
        self.btn_browse.setObjectName("btn_browse")
        self.horizontalLayout.addWidget(self.btn_browse)
        self._2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_browse)
        self.lbl_location = QtWidgets.QLabel(self.frame_nbOpt)
        self.lbl_location.setObjectName("lbl_location")
        self._2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_location)
        self.frame_options.addTab(self.frame_nbOpt, "")
        self.vboxlayout.addWidget(self.frame_options)
        self.lbl_ul = QtWidgets.QLabel(self.main_widget)
        sizePolicy = QtWi2dgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_ul.sizePolicy().hasHeightForWidth())
        self.lbl_ul.setSizePolicy(sizePolicy)
        self.lbl_ul.setObjectName("lbl_ul")
        self.vboxlayout.addWidget(self.lbl_ul)
        self.lcd_upload = QtWidgets.QLCDNumber(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_upload.sizePolicy().hasHeightForWidth())
        self.lcd_upload.setSizePolicy(sizePolicy)
        self.lcd_upload.setMinimumSize(QtCore.QSize(80, 30))
        self.lcd_upload.setMaximumSize(QtCore.QSize(50, 45))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcd_upload.setFont(font)
        self.lcd_upload.setStyleSheet("color:rgb(170, 0, 0)")
        self.lcd_upload.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_upload.setDigitCount(2)
        self.lcd_upload.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_upload.setProperty("intValue", 7)
        self.lcd_upload.setObjectName("lcd_upload")
        self.vboxlayout.addWidget(self.lcd_upload, 0, QtCore.Qt.AlignHCenter)
        self.btn_start = QtWidgets.QPushButton(self.main_widget)
        self.btn_start.setObjectName("btn_start")
        self.vboxlayout.addWidget(self.btn_start)
        self.frame_run = QtWidgets.QFrame(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_run.sizePolicy().hasHeightForWidth())
        self.frame_run.setSizePolicy(sizePolicy)
        self.frame_run.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_run.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_run.setObjectName("frame_run")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_run)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_nb = QtWidgets.QPushButton(self.frame_run)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_nb.sizePolicy().hasHeightForWidth())
        self.btn_nb.setSizePolicy(sizePolicy)
        self.btn_nb.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_nb.setMaximumSize(QtCore.QSize(400, 125))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/nb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_nb.setIcon(icon)
        self.btn_nb.setIconSize(QtCore.QSize(50, 50))
        self.btn_nb.setObjectName("btn_nb")
        self.horizontalLayout_2.addWidget(self.btn_nb)
        self.btn_mysql = QtWidgets.QPushButton(self.frame_run)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mysql.sizePolicy().hasHeightForWidth())
        self.btn_mysql.setSizePolicy(sizePolicy)
        self.btn_mysql.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_mysql.setMaximumSize(QtCore.QSize(400, 125))
        self.btn_mysql.setObjectName("btn_mysql")
        self.horizontalLayout_2.addWidget(self.btn_mysql)
        self.vboxlayout.addWidget(self.frame_run)
        self.txt_madewithlove = QtWidgets.QLabel(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_madewithlove.sizePolicy().hasHeightForWidth())
        self.txt_madewithlove.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.txt_madewithlove.setFont(font)
        self.txt_madewithlove.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.txt_madewithlove.setOpenExternalLinks(True)
        self.txt_madewithlove.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByKeyboard | QtCore.Qt.LinksAccessibleByMouse)
        self.txt_madewithlove.setObjectName("txt_madewithlove")
        self.vboxlayout.addWidget(self.txt_madewithlove)
        MainWindow.setCentralWidget(self.main_widget)
        self.lbl_cw.setBuddy(self.sb_cw)
        self.lbl_date.setBuddy(self.dt_date)
        self.lbl_topic.setBuddy(self.cb_topic)
        self.lbl_description.setBuddy(self.txt_description)
        self.txt_ulInterval.setBuddy(self.sb_time)
        self.lbl_fileName.setBuddy(self.txt_fileName)
        self.lbl_location.setBuddy(self.txt_folderLocation)

        self.retranslateUi(MainWindow)
        self.frame_options.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_signIn, self.frame_options)
        MainWindow.setTabOrder(self.frame_options, self.sb_cw)
        MainWindow.setTabOrder(self.sb_cw, self.dt_date)
        MainWindow.setTabOrder(self.dt_date, self.cb_topic)
        MainWindow.setTabOrder(self.cb_topic, self.txt_description)
        MainWindow.setTabOrder(self.txt_description, self.sb_time)
        MainWindow.setTabOrder(self.sb_time, self.cb_timeUnit)
        MainWindow.setTabOrder(self.cb_timeUnit, self.cb_fileSave)
        MainWindow.setTabOrder(self.cb_fileSave, self.txt_fileName)
        MainWindow.setTabOrder(self.txt_fileName, self.txt_folderLocation)
        MainWindow.setTabOrder(self.txt_folderLocation, self.btn_browse)
        MainWindow.setTabOrder(self.btn_browse, self.btn_nb)
        MainWindow.setTabOrder(self.btn_nb, self.btn_mysql)
        MainWindow.setTabOrder(self.btn_mysql, self.btn_start)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto Upload to Drive"))
        self.btn_signIn.setText(_translate("MainWindow", "Sign Out"))
        self.lbl_welcome.setText(_translate("MainWindow", "Welcome Shubham Rao! Have a nice day!"))
        self.lbl_cw.setText(_translate("MainWindow", "Classwork/Period No."))
        self.sb_cw.setPrefix(_translate("MainWindow", "C.W. "))
        self.lbl_date.setText(_translate("MainWindow", "Date:"))
        self.lbl_topic.setText(_translate("MainWindow", "Topic:"))
        self.cb_topic.setItemText(0, _translate("MainWindow", "Java"))
        self.cb_topic.setItemText(1, _translate("MainWindow", "MySQL"))
        self.lbl_description.setText(
            _translate("MainWindow", "<html><head/><body><p>Description/Name:<br/>(Recommended)</p></body></html>"))
        self.txt_description.setDocumentTitle(_translate("MainWindow", "Practical Description"))
        self.frame_options.setTabText(self.frame_options.indexOf(self.frame_info), _translate("MainWindow", "Info"))
        self.txt_ulInterval.setText(_translate("MainWindow", "Upload Interval:"))
        self.cb_timeUnit.setItemText(0, _translate("MainWindow", "Minutes"))
        self.cb_timeUnit.setItemText(1, _translate("MainWindow", "Seconds"))
        self.cb_fileSave.setText(_translate("MainWindow", "Upload on File Save [EXPERIMENTAL]"))
        self.lbl_fileName.setText(_translate("MainWindow", "File Name:"))
        self.txt_fileName.setText(_translate("MainWindow", ".zip"))
        self.frame_options.setTabText(self.frame_options.indexOf(self.frame_ulOpt),
                                      _translate("MainWindow", "Upload Options"))
        self.btn_browse.setText(_translate("MainWindow", "Browse..."))
        self.lbl_location.setText(_translate("MainWindow", "Project Location:"))
        self.frame_options.setTabText(self.frame_options.indexOf(self.frame_nbOpt),
                                      _translate("MainWindow", "NetBeans Options"))
        self.lbl_ul.setText(_translate("MainWindow", "Uploads Done:"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_nb.setText(_translate("MainWindow", "Run NetBeans"))
        self.btn_mysql.setText(_translate("MainWindow", "Run MySQL"))
        self.txt_madewithlove.setText(_translate("MainWindow",
                                                 "<html><head/><body><p><span style=\" color:#0000ff;\">Made with </span><span style=\" color:#ff0000;\">❤️ </span><span style=\" color:#0000ff;\">and code by </span><a href=\"https://cshubhamrao.me\"><span style=\" text-decoration: underline; color:#aa0000;\">Shubham Rao</span></a></p></body></html>"))
